name: 'Create Release'
inputs:
  github_token:
    description: '"Contents" repository permissions (write)'
    required: true
  owner:
    description: 'Owner of the repository if it is not the current one'
    required: false
  repository:
    description: 'Repository on which to release. Used only if you want to create the release on another repo'
    required: false
  commitish:
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists.'
    required: true
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
  body:
    description: 'Text describing the contents of the tag.'
    required: false
  prerelease:
    description: '`true` to identify the release as a prerelease. `false` to identify the release as a full release.'
    required: false
    default: false
  generate_release_notes:
    description: 'Whether to automatically generate the name and body for this release.'
    required: false
    default: true
outputs:
  release-id:
    description: 'Release ID'
    value: ${{ steps.create-release.outputs.release-id }}
  created:
    description: 'Created'
    value: ${{ steps.create-release.outputs.created }}
runs:
  using: composite
  steps:
    - name: 'Set env'
      run: |
        OWNER="${{ github.repository_owner }}"
        [ -n "${{ inputs.owner }}" ] && OWNER="${{ inputs.owner }}"
        echo "OWNER=$OWNER" >> "$GITHUB_ENV"

        REPOSITORY=$(echo "${{ github.repository }}" | sed -e 's,.*/\(.*\),\1,')
        [ -n "${{ inputs.repository }}" ] && REPOSITORY="${{ inputs.repository }}"
        echo "REPOSITORY=$REPOSITORY" >> "$GITHUB_ENV"

        BODY=""
        [ -n "${{ inputs.body }}" ] && BODY="${{ inputs.body }}"
        echo "BODY=$BODY" >> "$GITHUB_ENV"

        PRERELEASE=""
        [ -n "${{ inputs.prerelease }}" ] && PRERELEASE="${{ inputs.prerelease }}"
        echo "PRERELEASE=$PRERELEASE" >> "$GITHUB_ENV"

        GENERATE_RELEASE_NOTES=""
        [ -n "${{ inputs.generate_release_notes }}" ] && GENERATE_RELEASE_NOTES="${{ inputs.generate_release_notes }}"
        echo "GENERATE_RELEASE_NOTES=$GENERATE_RELEASE_NOTES" >> "$GITHUB_ENV"
      shell: bash
    - name: 'Get release id'
      run: |
        RESPONSE=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPOSITORY }}/releases \
        )

        RELEASE_ID=$(echo $RESPONSE | jq '.[] | select(.tag_name=="${{ inputs.tag_name }}") | .id')
        echo "RELEASE_ID=$RELEASE_ID" >> "$GITHUB_ENV"
      shell: bash
    - name: 'Create release'
      id: create-release
      run: |
        if [ -n "${{ env.RELEASE_ID }}" ]; then
          echo "Release for ${{ inputs.tag_name }} is already exist."

          echo "release-id=$RELEASE_ID" >> "$GITHUB_OUTPUT"
          echo "created=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        RESPONSE=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPOSITORY }}/releases \
          -d '{"tag_name":"${{ inputs.tag_name }}","target_commitish":"${{ inputs.commitish }}","name":"${{ inputs.tag_name }}","body":"${{ env.BODY }}","draft":false,"prerelease":${{ env.PRERELEASE }},"generate_release_notes":${{ env.GENERATE_RELEASE_NOTES }}}' \
        )

        STATUS=$(echo $RESPONSE | jq '.status')
        if [ "$STATUS" != null ]; then
          echo "Failed to create release for ${{ inputs.tag_name }}."
          echo "HTTP status code: $STATUS"
          exit 1
        else
          echo "Succeed to create release for ${{ inputs.tag_name }}."
        fi

        RELEASE_ID=$(echo "$RESPONSE" | jq '.id')

        echo "release-id=$RELEASE_ID" >> "$GITHUB_OUTPUT"
        echo "created=true" >> "$GITHUB_OUTPUT"
      shell: bash
