name: 'Test Local Action'

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Owner'
        type: string
        required: false
      repository:
        description: 'Repository'
        type: string
        required: false
      commitish:
        description: 'Commitish'
        type: string
        required: true
        default: 'master'
      tag_name:
        description: 'Tag Name'
        type: string
        required: true
        default: 'v0.1.0'
      prerelease:
        description: 'PreRelease'
        type: boolean
        required: false
        default: false
      generate_release_notes:
        description: 'Generate Release Notes'
        type: boolean
        required: false
        default: true

jobs:
  test-local-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Test local action'
        id: test-local-action
        uses: ./
        with:
          owner: ${{ inputs.owner }}
          repository: ${{ inputs.repository }}
          commitish: ${{ inputs.commitish }}
          tag_name: ${{ inputs.tag_name }}
          prerelease: ${{ inputs.prerelease }}
          generate_release_notes: ${{ inputs.generate_release_notes }}
      - name: 'Print outputs'
        run: |
          echo "created: ${{ steps.test-local-action.outputs.created }}"
          echo "release-id: ${{ steps.test-local-action.outputs.release-id }}"
